apiVersion: v1
kind: Secret
metadata:
  name: fraud-detection-secrets
  namespace: fraud-detection
type: Opaque
stringData:
  DAGSHUB_USERNAME: "emmanuelmassawe200"
  DAGSHUB_TOKEN: "your-dagshub-token-here"  # Replace with actual token
  DAGSHUB_REPO: "credit-card-fraud-detection"
  MLFLOW_TRACKING_URI: "https://dagshub.com/emmanuelmassawe200/credit-card-fraud-detection.mlflow"